; Mod Loader Folder Config File
[Folder.Config]
Profile = Default
PriorityLimit = 100

[Profiles.Default.Config]
IgnoreAllMods = false
ExcludeAllMods = false

[Profiles.Default.Priority]
servers/chile_police_roleplay=90

[Profiles.Default.IgnoreFiles]

[Profiles.Default.IgnoreMods]
_ignore

[Profiles.Default.IncludeMods]

[Profiles.Default.ExclusiveMods]
